import "./globals.css";
import { Poppins, Inter } from "next/font/google";
import Navbar from "@/components/nav/Navbar";

export const poppins = Poppins({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const inter = Inter({
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} p-6 bg-slate-950 min-h-screen`}
			>
				<Navbar />
				<main>{children}</main>
			</body>
		</html>
	);
}
